url: "https://sera-l.github.io/SuperTux.github.io/"
baseurl: "//SuperTux.github.io/"
name: SuperTux
markdown: kramdown
highlighter: rouge
exclude:
  - README.md
output: true
description: SuperTux is an open-source classic 2D jump'n run sidescroller game in a style similar to the original Super Mario games.
